name: Build Kernel with BBR v3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libncurses-dev libssl-dev libelf-dev bison bc flex rsync debhelper vim gcc make zlib1g-dev libbz2-dev fakeroot kmod libncurses5 dkms jq curl

      - name: Get latest kernel version
        id: get_kernel_version
        run: |
          LATEST_KERNEL_VERSION=$(git ls-remote --tags https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git \
            | awk -F'/' '{print $3}' \
            | grep -E '^v[0-9]+\.[0-9]+(\.[0-9]+)?$' \
            | grep -v -E "rc|test" \
            | sort -V \
            | tail -1)
          echo "LATEST_KERNEL_VERSION=$LATEST_KERNEL_VERSION" >> $GITHUB_OUTPUT

      - name: Get latest GitHub release
        id: get_github_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: byJoey/Actions-bbr-v3
        run: |
          LATEST_GITHUB_RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO/releases \
            | jq -r '[.[] | select(.prerelease == false)][0].tag_name')
          echo "LATEST_GITHUB_RELEASE=$LATEST_GITHUB_RELEASE" >> $GITHUB_OUTPUT

      - name: Compare Versions
        run: |
          if [ "${{ steps.get_github_release.outputs.LATEST_GITHUB_RELEASE }}" = "${{ steps.get_kernel_version.outputs.LATEST_KERNEL_VERSION }}" ]; then
            echo "GitHub release version equals latest kernel version. No update needed."
            exit 0
          fi
          echo "Need to build a new release."

      - name: Prepare build directory
        run: |
          rm -rf linux kernel_release kernel_release_*.tar.gz
          mkdir -p kernel_release

      - name: Download and prepare kernel source (ARM64)
        run: |
          # 下载最新内核源码
          git clone --branch ${{ steps.get_kernel_version.outputs.LATEST_KERNEL_VERSION }} --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          cd linux

          # 获取内核版本
          KERNEL_VERSION=$(make kernelversion)
          echo "Kernel version: $KERNEL_VERSION"

          # 添加BBR v3源码
          git remote add google-bbr https://github.com/google/bbr.git
          git fetch google-bbr
          git checkout google-bbr/v3

          # 修改 Makefile 版本信息
          sed -i "s/^VERSION = .*/VERSION = ${KERNEL_VERSION%%.*}/" Makefile
          sed -i "s/^PATCHLEVEL = .*/PATCHLEVEL = $(echo $KERNEL_VERSION | cut -d. -f2)/" Makefile
          sed -i "s/^SUBLEVEL = .*/SUBLEVEL = $(echo $KERNEL_VERSION | cut -d. -f3 | cut -d- -f1)/" Makefile

          # 下载配置文件
          curl -L https://raw.githubusercontent.com/byJoey/Actions-bbr-v3/refs/heads/main/arm64.config -o arm64.config
          cp arm64.config .config
          yes "" | make oldconfig
          sed -i '/CONFIG_SYSTEM_TRUSTED_KEYS/d' .config
          echo 'CONFIG_SYSTEM_TRUSTED_KEYS=""' >> .config
          sed -i 's/CONFIG_DEBUG_INFO=y/CONFIG_DEBUG_INFO=n/' .config

          # 编译 ARM64 内核
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LOCALVERSION=-joeyblog-joeyblog.net KBUILD_BUILD_DEBUG_INFO=n bindeb-pkg -j$(nproc)
          
          # 保存结果
          cd ..
          mkdir -p kernel_release/arm64
          mv linux-image-*.deb linux-headers-*.deb kernel_release/arm64/
          tar -czvf kernel_release_arm64_${KERNEL_VERSION}.tar.gz -C kernel_release/arm64 .

          echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV

      - name: Download and prepare kernel source (x86_64)
        run: |
          KERNEL_VERSION=${{ env.KERNEL_VERSION }}
          # 再次下载源码进行x86_64编译
          rm -rf linux
          git clone --branch v$KERNEL_VERSION --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          cd linux

          # 添加 BBR v3
          git remote add google-bbr https://github.com/google/bbr.git
          git fetch google-bbr
          git checkout google-bbr/v3

          # 修改 Makefile 版本信息
          sed -i "s/^VERSION = .*/VERSION = ${KERNEL_VERSION%%.*}/" Makefile
          sed -i "s/^PATCHLEVEL = .*/PATCHLEVEL = $(echo $KERNEL_VERSION | cut -d. -f2)/" Makefile
          sed -i "s/^SUBLEVEL = .*/SUBLEVEL = $(echo $KERNEL_VERSION | cut -d. -f3 | cut -d- -f1)/" Makefile

          # 下载x86_64配置
          curl -L https://raw.githubusercontent.com/byJoey/Actions-bbr-v3/refs/heads/main/x86-64.config -o .config
          yes "" | make oldconfig
          sed -i '/CONFIG_SYSTEM_TRUSTED_KEYS/d' .config
          echo 'CONFIG_SYSTEM_TRUSTED_KEYS=""' >> .config
          sed -i 's/CONFIG_DEBUG_INFO=y/CONFIG_DEBUG_INFO=n/' .config

          # 编译 x86_64 内核
          make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu- LOCALVERSION=-joeyblog-joeyblog.net KBUILD_BUILD_DEBUG_INFO=n bindeb-pkg -j$(nproc)

          cd ..
          mkdir -p kernel_release/x86_64
          mv linux-image-*.deb linux-headers-*.deb kernel_release/x86_64/
          tar -czvf kernel_release_x86_64_${KERNEL_VERSION}.tar.gz -C kernel_release/x86_64 .

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: byJoey/Actions-bbr-v3
          KERNEL_VERSION: ${{ env.KERNEL_VERSION }}
        run: |
          # 创建发行版
          RELEASE_RESPONSE=$(curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"v$KERNEL_VERSION\", \"name\": \"Kernel $KERNEL_VERSION (arm64 & x86_64)\", \"body\": \"Auto-generated release for kernel version $KERNEL_VERSION (arm64 & x86_64)\"}" \
            https://api.github.com/repos/$REPO/releases)
          UPLOAD_URL=$(echo $RELEASE_RESPONSE | jq -r .upload_url | sed -e "s/{?name,label}//")

          if [ "$UPLOAD_URL" == "null" ]; then
            echo "Failed to create release."
            echo "$RELEASE_RESPONSE"
            exit 1
          fi

          # 上传ARM64
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/gzip" --data-binary @kernel_release_arm64_${KERNEL_VERSION}.tar.gz "$UPLOAD_URL?name=kernel_release_arm64_${KERNEL_VERSION}.tar.gz"
          
          # 上传x86_64
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/gzip" --data-binary @kernel_release_x86_64_${KERNEL_VERSION}.tar.gz "$UPLOAD_URL?name=kernel_release_x86_64_${KERNEL_VERSION}.tar.gz"

          echo "Release and uploads completed."
