name: 自动内核编译与BBR v3安装

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 自动运行
  workflow_dispatch: # 支持手动触发

jobs:
  build:
    name: 编译内核（Docker 容器，Debian 12）
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装编译所需依赖
        run: |
          apt-get update
          apt-get install -y \
            git build-essential libncurses-dev libssl-dev libelf-dev bison bc flex rsync \
            debhelper vim gcc make zlib1g-dev libbz2-dev fakeroot kmod libncurses5 dkms jq curl \
            gcc-aarch64-linux-gnu

      - name: 获取最新内核版本
        id: kernel_version
        run: |
          LATEST_KERNEL_VERSION=$(curl -s https://www.kernel.org/releases.json | jq -r '.latest_stable.version')
          if [[ -z "$LATEST_KERNEL_VERSION" ]]; then
            echo "无法获取最新内核版本，请检查网络或 kernel.org 是否可访问。"
            exit 1
          fi
          echo "最新内核版本为：$LATEST_KERNEL_VERSION"
          echo "::set-output name=version::$LATEST_KERNEL_VERSION"

      - name: 获取 GitHub 最新发布版本
        id: github_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO="byJoey/Actions-bbr-v3"
          LATEST_GITHUB_RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO/releases | jq -r '[.[] | select(.prerelease == false)][0].tag_name')
          GITHUB_RELEASE_CLEANED=${LATEST_GITHUB_RELEASE#v}
          echo "GitHub 最新发布版本为：$GITHUB_RELEASE_CLEANED"
          echo "::set-output name=github_version::$GITHUB_RELEASE_CLEANED"

      - name: 比较版本
        run: |
          if [[ "${{ steps.github_release.outputs.github_version }}" == "${{ steps.kernel_version.outputs.version }}" ]]; then
            echo "GitHub 发布的版本与最新内核版本一致，无需更新。"
            exit 0
          else
            echo "版本不一致，继续执行后续步骤。"
          fi

      - name: 编译 ARM64 内核
        run: |
          echo "下载内核源码..."
          git clone --branch v${{ steps.kernel_version.outputs.version }} --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          cd linux

          echo "获取当前内核版本..."
          KERNEL_VERSION=$(make kernelversion)
          echo "当前内核版本为：$KERNEL_VERSION"

          echo "添加 BBR v3 源码仓库..."
          git remote add google-bbr https://github.com/google/bbr.git
          git fetch google-bbr
          git checkout google-bbr/v3

          echo "写回 Makefile..."
          sed -i "s/^VERSION = .*/VERSION = ${KERNEL_VERSION%%.*}/" Makefile
          sed -i "s/^PATCHLEVEL = .*/PATCHLEVEL = $(echo $KERNEL_VERSION | cut -d. -f2)/" Makefile
          sed -i "s/^SUBLEVEL = .*/SUBLEVEL = $(echo $KERNEL_VERSION | cut -d. -f3 | cut -d- -f1)/" Makefile

          echo "配置 ARM64 内核..."
          curl -L https://raw.githubusercontent.com/byJoey/Actions-bbr-v3/refs/heads/main/arm64.config -o .config
          make ARCH=arm64 olddefconfig
          sed -i '/CONFIG_SYSTEM_TRUSTED_KEYS/d' .config
          echo 'CONFIG_SYSTEM_TRUSTED_KEYS=""' >> .config
          sed -i 's/CONFIG_DEBUG_INFO=y/CONFIG_DEBUG_INFO=n/' .config

          echo "编译 ARM64 内核..."
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LOCALVERSION=-joeyblog-joeyblog.net bindeb-pkg -j$(nproc)
          mkdir -p ../kernel_release/arm64
          mv ../*.deb ../kernel_release/arm64/
          cd ..

      - name: 编译 x86_64 内核
        run: |
          echo "重新下载内核源码..."
          rm -rf linux
          git clone --branch v${{ steps.kernel_version.outputs.version }} --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          cd linux

          echo "获取当前内核版本..."
          KERNEL_VERSION=$(make kernelversion)
          echo "当前内核版本为：$KERNEL_VERSION"

          echo "添加 BBR v3 源码仓库..."
          git remote add google-bbr https://github.com/google/bbr.git
          git fetch google-bbr
          git checkout google-bbr/v3

          echo "写回 Makefile..."
          sed -i "s/^VERSION = .*/VERSION = ${KERNEL_VERSION%%.*}/" Makefile
          sed -i "s/^PATCHLEVEL = .*/PATCHLEVEL = $(echo $KERNEL_VERSION | cut -d. -f2)/" Makefile
          sed -i "s/^SUBLEVEL = .*/SUBLEVEL = $(echo $KERNEL_VERSION | cut -d. -f3 | cut -d- -f1)/" Makefile

          echo "配置 x86_64 内核..."
          curl -L https://raw.githubusercontent.com/byJoey/Actions-bbr-v3/refs/heads/main/x86-64.config -o .config
          make ARCH=x86_64 olddefconfig
          sed -i '/CONFIG_SYSTEM_TRUSTED_KEYS/d' .config
          echo 'CONFIG_SYSTEM_TRUSTED_KEYS=""' >> .config
          sed -i 's/CONFIG_DEBUG_INFO=y/CONFIG_DEBUG_INFO=n/' .config

          echo "编译 x86_64 内核..."
          make ARCH=x86_64 LOCALVERSION=-joeyblog-joeyblog.net bindeb-pkg -j$(nproc)
          mkdir -p ../kernel_release/x86_64
          mv ../*.deb ../kernel_release/x86_64/
          cd ..

      - name: 上传到 GitHub Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            kernel_release/arm64/*.deb
            kernel_release/x86_64/*.deb
          body: |
            自动生成的 ${{ steps.kernel_version.outputs.version }} 版本内核（ARM64 和 x86_64）
