name: 自动内核编译与BBR v3安装

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 自动运行
  workflow_dispatch: # 支持手动触发

jobs:
  build-arm64:
    name: 编译 ARM64 内核
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 ARM64 依赖
        run: |
          apt-get update
          apt-get install -y \
            git build-essential libncurses-dev libssl-dev libelf-dev bison bc flex rsync \
            debhelper vim gcc make zlib1g-dev libbz2-dev fakeroot kmod libncurses5 dkms jq curl \
            gcc-12-aarch64-linux-gnu cpio pkg-config python3 python3-distutils

      - name: 编译 ARM64 内核
        run: |
          echo "下载内核源码..."
          git clone --branch v6.1 --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          cd linux

          echo "配置内核..."
          curl -L https://raw.githubusercontent.com/byJoey/Actions-bbr-v3/main/arm64.config -o .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
          sed -i '/CONFIG_SYSTEM_TRUSTED_KEYS/d' .config
          echo 'CONFIG_SYSTEM_TRUSTED_KEYS=""' >> .config

          echo "编译 ARM64 内核..."
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LOCALVERSION=-joeyblog bindeb-pkg -j$(nproc)

          echo "保存结果..."
          mkdir -p ../kernel_release/arm64
          mv ../*.deb ../kernel_release/arm64/

  build-x86_64:
    name: 编译 x86_64 内核
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 x86_64 依赖
        run: |
          apt-get update
          apt-get install -y \
            git build-essential libncurses-dev libssl-dev libelf-dev bison bc flex rsync \
            debhelper vim gcc make zlib1g-dev libbz2-dev fakeroot kmod libncurses5 dkms jq curl \
            gcc-multilib cpio pkg-config python3 python3-distutils

      - name: 编译 x86_64 内核
        run: |
          echo "下载内核源码..."
          git clone --branch v6.1 --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          cd linux

          echo "配置内核..."
          curl -L https://raw.githubusercontent.com/byJoey/Actions-bbr-v3/main/x86-64.config -o .config
          make ARCH=x86_64 olddefconfig
          sed -i '/CONFIG_SYSTEM_TRUSTED_KEYS/d' .config
          echo 'CONFIG_SYSTEM_TRUSTED_KEYS=""' >> .config

          echo "编译 x86_64 内核..."
          make ARCH=x86_64 LOCALVERSION=-joeyblog bindeb-pkg -j$(nproc)

          echo "保存结果..."
          mkdir -p ../kernel_release/x86_64
          mv ../*.deb ../kernel_release/x86_64/

  upload:
    name: 上传到 GitHub Releases
    needs:
      - build-arm64
      - build-x86_64
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 上传到 GitHub Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            kernel_release/arm64/*.deb
            kernel_release/x86_64/*.deb
          body: |
            自动生成的内核包，支持 ARM64 和 x86_64。
